version: "3.9"
services:
  sam-local:
    build:
      context: .
      dockerfile: ./docker/sam-local/Dockerfile
    ports:
      - 3005:3005
    working_dir: $PWD
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD:$PWD
    tty: true
    stdin_open: true
